import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})


export class ConstantsService {

  constructor() { }


  drawings_filters=["Abstrait","Animaux","Animés","Architecture","Art","Botanique","BD","Campagne","Caricatural","Cartoons","Cinéma","Combats","Comics","Culture","Décoration","Design","Enigmatique","Enfants","Fanart","Fanfiction","Fantaisie","Femmes","Fête","Fresque","Guerre","Guerrier","Graffiti","Héroïque","Histoire","Hommes","Horreur","Humour","Immeubles","Intérieur","Kawaii","Maisons",
  "Mangas","Monstre","Montagnes","Motos","Nature","Nature morte","Paysage","Personnages","Photographie","Portrait",
  "Réaliste","Religion","Retro","Romantique","Rural","SF","Sociologie","Spatial","Sport","Survie","Transports","Urbanisme","Véhicules","Villes","Voitures","Voyage","Western"]
  writings_filters=["Action","Animaux","Animés","Art","Aventure","Autobiographie","BD","Caricatural","Cartoons","Comics","Drame","Enigmatique","Enfants","Epique","Epistolaire","Esotérisme","Fanfiction","Fantaisie","Guerre","Héroïque","Histoire","Horreur","Humour","Journalisme","Mangas","Pensées","Philosophie","Polar",
  "Policier","Réaliste","Réflexions","Religion","Romantique","Satirique","SF","Sociologie","Spatial","Spiritualité","Sport","Survie","Thriller","Voyage","Webtoon","Western"];
  comics_filters=["Action","Animaux","Art","Aventure","Biographie","Caricatural","Combats","Drame","Enigmatique","Enfants","Epique","Esotérisme","Fanfiction","Fantaisie","Fantastique","Guerre","Héroïque","Histoire","Horreur","Humour","Josei","Journalisme","Kawaii","Kodomo","Nekketsu","Pantso shoto","Philosophie","Photographie","Polar","Policier","Religion","Romantique","Satirique","SF","Seinen","Shojo","Shonen","Sociologie","Spatial","Sport","Survie","Thriller","Voyage","Western","Yaoi","Yuri"];
  
  type_of_accounts=["Artiste","Éditeur","Fan"];
  
  ads_types=["Tout","Bandes dessinées","BD européennes","Comics","Manga","Webtoon","Dessins","Dessin digital",
  "Dessin traditionnel","Écrits","Article","Poésie","Roman","Roman illustré","Scénario"];
  ads_targets=["Tout","Professionnel de l'édition","Professionnel non artiste","Artiste en tout genre","Auteur de bandes dessinées","Ecrivain","Dessinateur","Scénariste","Tout public"];
  ads_descriptions=["Tout","Professionnel de l'édition","Professionnel non artiste","Artiste en tout genre","Auteur de bandes dessinées","Ecrivain","Dessinateur","Scénariste"]
  price_types_remunerated=["Tout","Annuel","CDD","CDI","Journalier","Mensuel","Par mission"]
  price_types_services=["Tout","Produits","Services"];
  offers_or_demands=["Tout","Offre","Demande"];

  list_of_categories=["Articles","BD","Comics","Mangas","Livres","Livres jeunesses"];
  list_of_skills=[
  "Articles", "Articles de presse", "Articles historiques", "Articles philosophiques/sociologiques", 
  "Articles scientifiques", "Articles sportifs", 
  
  "Coloriage feutre", "Coloriage graphique",

  "Dessin BD", "Dessin Comics", "Dessin Mangas", "Dessin action/combat", 
  "Dessin architectural", "Dessin arme", "Dessin au crayon", "Dessin caricatural", "Dessin colorié", 
  "Dessin d'horreur", "Dessin de mouvements", "Dessin digital", "Dessin encre de Chine", "Dessin enfants", 
  "Dessin fantaisie", "Dessin feutre", "Dessin gore", "Dessin guerre","Dessin kawaii", "Dessin ludique", 
  "Dessin lumières & ombres", "Dessin noir & blanc", "Dessin paysage", "Dessin pers. fiction", 
  "Dessin pers. réaliste", "Dessin personnages", "Dessin portrait", "Dessin pour adulte", 
  "Dessin romantique", "Dessin rural", "Dessin réaliste",  "Dessin science-fiction","Dessin sketch", 
  "Dessin story-board","Dessin tablette graphique", "Dessin traditionnel", "Dessin urbain", 
  "Dessin vectoriel", "Dessin véhicules",
  
  "Écrit ados", "Écrit adulte", "Écrit autobiographique", "Écrit aventure", 
  "Écrit de guerre", "Écrit dramatique", "Écrit éducatif", "Écrit enfants", "Écrit épistolaire", 
  "Écrit ésotérique", "Écrit historique", "Écrit horreur", "Écrit héroïque", "Écrit mystérieux",
  "Écrit nouvelles", "Écrit pensées & réflexions", "Écrit philosophique", "Écrit polar", 
  "Écrit policier", "Écrit poésie", "Écrit religieux", "Écrit romans", 
  "Écrit romantique", "Écrit réaliste", "Écrit science-fiction", "Écrit spirituel", 
  "Écrit suspens", "Écrit voyage", ,
  
  "Scénario", "Scénario BD", "Scénario Comics", "Scénario Mangas", "Scénario action/combat", 
  "Scénario ados", "Scénario adulte", "Scénario aventure", "Scénario de guerre", "Scénario de survie", 
  "Scénario dramatique","Scénario éducatif",  "Scénario enfants","Scénario énigmatique", 
  "Scénario épique", "Scénario ésotérique", "Scénario fanfiction", "Scénario fantaisie", 
  "Scénario historique", "Scénario horreur", "Scénario humoristique", "Scénario héroïque", 
  "Scénario intergalactique", "Scénario mystique", "Scénario mystérieux", "Scénario philosophique", 
  "Scénario policier", "Scénario religieux", "Scénario romantique", "Scénario réaliste", 
  "Scénario satirique", "Scénario science-fiction", "Scénario seinen", "Scénario shojo", "Scénario shônen", "Scénario sociologique", 
  "Scénario spirituel", "Scénario sport", "Scénario suspens", "Scénario voyage", "Scénario western", 
  
  
  "Logiciel Adobe", "Logiciel Adobe After Effects","Logiciel Adobe Creative Cloud tools", 
  "Logiciel Adobe Illustrator", "Logiciel Adobe Photoshop", "Logiciel Astute Phantasm", 
  "Logiciel Clip Studio Paint", "Logiciel IOS", "Logiciel Linux", "Logiciel Microsoft Office", "Logiciel Paint",
  "Logiciel Procreate", "Logiciel Ron’s Brushes", "Logiciel Windows",]

  list_of_genres=["Action","Actualité","Ados","Adultes","Animalié","Art","Aventure","Autobiographie","BD",
  "Caricatural","Comics","Combats","Drame","Educatif","Enigmatique","Enfants","Epique","Epistolaire",
  "Esotérisme","Fanfiction","Fantaisie","Guerre","Héroïque","Historique","Horreur","Humoristique",
  "Journalisme","Kawaii","Ludique","Mangas","Mystère","Nouvelles","Pensées","Philosophie","Poésie","Polar","Policier",
  "Réaliste","Réflexions","Religion","Romans","Romantique","Satirique","Science fiction","Seinen","Shojo",
  "Shônen","Sociologie","Spatial","Spiritualité","Sport","Survie","Thriller","Voyage","Webtoon","Western"]

  list_of_countries=[
    'Aucun pays',
    "France",
    "Afghanistan", 
    "Afrique Centrale", 
    "Afrique du sud", 
    "Albanie", 
    "Algerie", 
    "Allemagne", 
    "Andorre", 
    "Angola", 
    "Anguilla", 
    "Arabie Saoudite", 
    "Argentine", 
    "Armenie", 
    "Australie", 
    "Autriche", 
    "Azerbaidjan", 
    "Bahamas", 
    "Bangladesh", 
    "Barbade", 
    "Bahrein", 
    "Belgique", 
    "Belize", 
    "Benin", 
    "Bermudes", 
    "Bielorussie", 
    "Bolivie", 
    "Botswana", 
    "Bhoutan", 
    "Boznie Herzegovine", 
    "Bresil", 
    "Brunei", 
    "Bulgarie", 
    "Burkina Faso", 
    "Burundi", 
    "Caiman", 
    "Cambodge", 
    "Cameroun", 
    "Canada", 
    "Canaries", 
    "Cap vert", 
    "Chili", 
    "Chine", 
    "Chypre", 
    "Colombie", 
    "Comores", 
    "Congo", 
    "Congo democratique", 
    "Cook", 
    "Coree du Nord", 
    "Coree du Sud", 
    "Costa Rica", 
    "Cote d'Ivoire", 
    "Croatie", 
    "Cuba", 
    "Danemark", 
    "Djibouti", 
    "Dominique", 
    "Egypte", 
    "Emirats Arabes Unis", 
    "Equateur", 
    "Erythree", 
    "Espagne", 
    "Estonie", 
    "Etats-Unis", 
    "Ethiopie", 
    "Falkland", 
    "Feroe", 
    "Fidji", 
    "Finlande", 
    "France", 
    "Gabon", 
    "Gambie", 
    "Georgie", 
    "Ghana", 
    "Gibraltar", 
    "Grece", 
    "Grenade", 
    "Groenland", 
    "Guadeloupe", 
    "Guam", 
    "Guatemala",
    "Guernesey", 
    "Guinee", 
    "Guinee Bissau", 
    "Guinee equatoriale", 
    "Guyana", 
    "Guyane Francaise ", 

    "Haiti", 
    "Hawaii", 
    "Honduras", 
    "Hong Kong", 
    "Hongrie", 

    "Inde", 
    "Indonesie", 
    "Iran", 
    "Iraq", 
    "Irlande", 
    "Islande", 
    "Israel", 
    "Italie", 

    "Jamaique", 
    "Jan Mayen", 
    "Japon", 
    "Jersey", 
    "Jordanie", 

    "Kazakhstan", 
    "Kenya", 
    "Kirghizstan", 
    "Kiribati", 
    "Koweit", 

    "Laos", 
    "Lesotho", 
    "Lettonie", 
    "Liban", 
    "Liberia", 
    "Liechtenstein", 
    "Lituanie", 
    "Luxembourg", 
    "Lybie", 

    "Macao", 
    "Macedoine", 
    "Madagascar", 
    "Madère", 
    "Malaisie", 
    "Malawi", 
    "Maldives", 
    "Mali", 
    "Malte", 
    "Man", 
    "Mariannes du Nord", 
    "Maroc", 
    "Marshall", 
    "Martinique", 
    "Maurice", 
    "Mauritanie", 
    "Mayotte", 
    "Mexique", 
    "Micronesie", 
    "Midway", 
    "Moldavie", 
    "Monaco", 
    "Mongolie", 
    "Montserrat", 
    "Mozambique", 
    "Namibie", 
    "Nauru", 
    "Nepal", 
    "Nicaragua", 
    "Niger", 
    "Nigeria", 
    "Niue", 
    "Norfolk", 
    "Norvege", 
    "Nouvelle Caledonie", 
    "Nouvelle Zelande", 
    "Oman", 
    "Ouganda", 
    "Ouzbekistan", 
    "Pakistan", 
    "Palau", 
    "Palestine", 
    "Panama", 
    "Papouasie Nouvelle Guinee", 
    "Paraguay", 
    "Pays Bas", 
    "Perou", 
    "Philippines", 
    "Pologne", 
    "Polynesie", 
    "Porto Rico", 
    "Portugal", 
    "Qatar", 
    "Republique Dominicaine", 
    "Republique Tcheque", 
    "Reunion", 
    "Roumanie", 
    "Royaume Uni", 
    "Russie", 
    "Rwanda", 
    "Sahara Occidental",
    "Sainte Lucie", 
    "Saint Marin", 
    "Salomon", 
    "Salvador", 
    "Samoa Occidentales",
    "Samoa Americaine", 
    "Sao Tome et Principe", 
    "Senegal", 
    "Seychelles", 
    "Sierra Leone",
    "Singapour", 
    "Slovaquie", 
    "Slovenie",
    "Somalie", 
    "Soudan", 
    "Sri Lanka", 
    "Suede", 
    "Suisse", 
    "Surinam", 
    "Swaziland", 
    "Syrie", 
    "Tadjikistan", 
    "Taiwan", 
    "Tonga", 
    "Tanzanie", 
    "Tchad", 
    "Thailande", 
    "Tibet", 
    "Timor Oriental", 
    "Togo", 
    "Trinite et Tobago", 
    "Tristan da cunha",
    "Tunisie", 
    "Turkmenistan", 
    "Turquie", 
    "Ukraine", 
    "Uruguay", 
    "Vanuatu", 
    "Vatican", 
    "Venezuela", 
    "Vierges Americaines", 
    "Vierges Britanniques", 
    "Vietnam", 
    "Wake", 
    "Wallis et Futuma", 
    "Yemen", 
    "Yougoslavie", 
    "Zambie", 
    "Zimbabwe",
  ]
  
}
